# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version from Discord Changelog'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          ref: no-variants
          
      # Put the version into the version file
      - name: Run a one-line script
        run: echo '${{ github.event.inputs.version }}' > '$GITHUB_WORKSPACE/p5e-data/VERSION'
        
      # Runs the data fetch
      - name: Update data
        run: python '$GITHUB_WORKSPACE/p5e-data/p5e-data-conversion/main.py -k -np -o $GITHUB_WORKSPACE/p5e-data/data' 
      
      # Add and commit changes
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update '${{ github.event.inputs.version }}'
